parameters:
    form.resolved_type_factory.class: ITE\FormBundle\Form\ResolvedFormTypeFactory

services:
    form.resolved_type_factory:
        class: %form.resolved_type_factory.class%
        arguments: [ @service_container, @ite_form.proxy_factory ]