parameters:
    ite_form.plugin.select2.class:                      ITE\FormBundle\SF\Plugin\Select2Plugin
    ite_form.plugin.tinymce.class:                      ITE\FormBundle\SF\Plugin\TinymcePlugin
    ite_form.plugin.bootstrap_colorpicker.class:        ITE\FormBundle\SF\Plugin\BootstrapColorpickerPlugin
    ite_form.plugin.bootstrap_spinedit.class:           ITE\FormBundle\SF\Plugin\BootstrapSpineditPlugin
    ite_form.plugin.bootstrap_datetimepicker.class:     ITE\FormBundle\SF\Plugin\BootstrapDatetimepickerPlugin
    ite_form.plugin.fileupload.class:                   ITE\FormBundle\SF\Plugin\FileuploadPlugin
    ite_form.plugin.fineuploader.class:                 ITE\FormBundle\SF\Plugin\FineuploaderPlugin
    ite_form.plugin.minicolors.class:                   ITE\FormBundle\SF\Plugin\MinicolorsPlugin
    ite_form.plugin.knob.class:                         ITE\FormBundle\SF\Plugin\KnobPlugin
    ite_form.plugin.starrating.class:                   ITE\FormBundle\SF\Plugin\StarratingPlugin
    ite_form.plugin.x_editable.class:                   ITE\FormBundle\SF\Plugin\XEditablePlugin
    ite_form.plugin.nod.class:                          ITE\FormBundle\SF\Plugin\NodPlugin
    ite_form.plugin.parsley.class:                      ITE\FormBundle\SF\Plugin\ParsleyPlugin
    ite_form.plugin.form.class:                         ITE\FormBundle\SF\Plugin\FormPlugin
    ite_form.plugin.bootstrap_daterangepicker.class:    ITE\FormBundle\SF\Plugin\BootstrapDaterangepickerPlugin
    ite_form.plugin.ion_range_slider.class:             ITE\FormBundle\SF\Plugin\IonRangeSliderPlugin
    ite_form.plugin.icheck.class:                       ITE\FormBundle\SF\Plugin\ICheckPlugin
    ite_form.plugin.inputmask.class:                    ITE\FormBundle\SF\Plugin\InputmaskPlugin
    ite_form.plugin.typeahead.class:                    ITE\FormBundle\SF\Plugin\TypeaheadPlugin
    ite_form.plugin.ckeditor.class:                     ITE\FormBundle\SF\Plugin\CKEditorPlugin
    ite_form.plugin.bootstrap_clockpicker.class:        ITE\FormBundle\SF\Plugin\BootstrapClockpickerPlugin

services:
    ite_form.plugin.select2:
        class: %ite_form.plugin.select2.class%
        tags:
            - { name: ite_form.plugin, alias: select2 }

    ite_form.plugin.tinymce:
        class: %ite_form.plugin.tinymce.class%
        tags:
            - { name: ite_form.plugin, alias: tinymce }

    ite_form.plugin.bootstrap_colorpicker:
        class: %ite_form.plugin.bootstrap_colorpicker.class%
        tags:
            - { name: ite_form.plugin, alias: bootstrap_colorpicker }

    ite_form.plugin.bootstrap_spinedit:
        class: %ite_form.plugin.bootstrap_spinedit.class%
        tags:
            - { name: ite_form.plugin, alias: bootstrap_spinedit }

    ite_form.plugin.bootstrap_datetimepicker:
        class: %ite_form.plugin.bootstrap_datetimepicker.class%
        tags:
            - { name: ite_form.plugin, alias: bootstrap_datetimepicker }

    ite_form.plugin.fileupload:
        class: %ite_form.plugin.fileupload.class%
        tags:
            - { name: ite_form.plugin, alias: fileupload }

    ite_form.plugin.fineuploader:
        class: %ite_form.plugin.fineuploader.class%
        tags:
            - { name: ite_form.plugin, alias: fineuploader }

    ite_form.plugin.minicolors:
        class: %ite_form.plugin.minicolors.class%
        tags:
            - { name: ite_form.plugin, alias: minicolors }

    ite_form.plugin.knob:
        class: %ite_form.plugin.knob.class%
        tags:
            - { name: ite_form.plugin, alias: knob }

    ite_form.plugin.starrating:
        class: %ite_form.plugin.starrating.class%
        tags:
            - { name: ite_form.plugin, alias: starrating }

    ite_form.plugin.x_editable:
        class: %ite_form.plugin.x_editable.class%
        tags:
            - { name: ite_form.plugin, alias: x_editable }

    ite_form.plugin.nod:
        class: %ite_form.plugin.nod.class%
        tags:
            - { name: ite_form.plugin, alias: nod }

    ite_form.plugin.parsley:
        class: %ite_form.plugin.parsley.class%
        tags:
            - { name: ite_form.plugin, alias: parsley }

    ite_form.plugin.form:
        class: %ite_form.plugin.form.class%
        tags:
            - { name: ite_form.plugin, alias: form }

    ite_form.plugin.bootstrap_daterangepicker:
        class: %ite_form.plugin.bootstrap_daterangepicker.class%
        tags:
            - { name: ite_form.plugin, alias: bootstrap_daterangepicker }

    ite_form.plugin.ion_range_slider:
        class: %ite_form.plugin.ion_range_slider.class%
        tags:
            - { name: ite_form.plugin, alias: ion_range_slider }

    ite_form.plugin.icheck:
        class: %ite_form.plugin.icheck.class%
        tags:
            - { name: ite_form.plugin, alias: icheck }

    ite_form.plugin.inputmask:
        class: %ite_form.plugin.inputmask.class%
        tags:
            - { name: ite_form.plugin, alias: inputmask }

    ite_form.plugin.typeahead:
        class: %ite_form.plugin.typeahead.class%
        tags:
            - { name: ite_form.plugin, alias: typeahead }

    ite_form.plugin.ckeditor:
        class: %ite_form.plugin.ckeditor.class%
        tags:
            - { name: ite_form.plugin, alias: ckeditor }

    ite_form.plugin.bootstrap_clockpicker:
        class: %ite_form.plugin.bootstrap_clockpicker.class%
        tags:
            - { name: ite_form.plugin, alias: bootstrap_clockpicker }
