parameters:
    ite_form.form.type_extension.plugin.form.class:      ITE\FormBundle\Form\Extension\Plugin\FormTypeExtension
    ite_form.form.form_type_extension.class:             ITE\FormBundle\Form\Extension\FormTypeExtension

    ite_form.form.google_font_type.class:                ITE\FormBundle\Form\Type\GoogleFontType

    ite_form.form.input_entity_type.class:               ITE\FormBundle\Form\Type\InputEntityType
    ite_form.form.markup_type.class:                     ITE\FormBundle\Form\Type\MarkupType

services:
    ite_form.form.type_extension.plugin.form:
        class:                                              %ite_form.form.type_extension.plugin.form.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.form_type_extension:
        class:                                              %ite_form.form.form_type_extension.class%
        arguments: [ @session, %ite_form.timezone% ]
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.google_font_type:
        class:                                              %ite_form.form.google_font_type.class%
        tags:
            - { name: form.type, alias: ite_google_font }

    ite_form.form.input_entity_type:
        class:                                              %ite_form.form.input_entity_type.class%
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: ite_input_entity }

    ite_form.form.markup_type:
        class:                                              %ite_form.form.markup_type.class%
        tags:
            - { name: form.type, alias: ite_markup }