parameters:
    ite_form.sf.extension.form.class:                    ITE\FormBundle\Service\SFFormExtension

    ite_form.twig.sf_form_extension.class:               ITE\FormBundle\Twig\Extension\SFFormExtension

    ite_form.form_validator.class:                       ITE\FormBundle\Service\FormValidator

    ite_form.form.form_type_extension.class:             ITE\FormBundle\Form\Core\Extension\FormTypeExtension
    ite_form.form.widget_form_type_extension.class:      ITE\FormBundle\Form\Core\Extension\WidgetFormTypeExtension

    ite_form.form.daterange_type.class:                  ITE\FormBundle\Form\Core\Type\DateRangeType
    ite_form.form.bootstrap_date_picker_type.class:      ITE\FormBundle\Form\Core\Type\BootstrapDatePickerType
    ite_form.form.bootstrap_datetime_picker_type.class:  ITE\FormBundle\Form\Core\Type\BootstrapDateTimePickerType
    ite_form.form.bootstrap_time_picker_type.class:      ITE\FormBundle\Form\Core\Type\BootstrapTimePickerType

    ite_form.form.ajax_entity_type.class:                ITE\FormBundle\Form\Doctrine\Type\AjaxEntityType

services:
    ite_form.sf.extension.form:
        class:                                              %ite_form.sf.extension.form.class%
        tags:
            - { name: ite_js.sf.extension, alias: form }

    ite_form.twig.sf_form_extension:
        class:                                              %ite_form.twig.sf_form_extension.class%
        arguments: [ @ite_js.sf ]
        tags:
            - { name: twig.extension }

    ite_form.form_validator:
        class:                                              %ite_form.form_validator.class%
        arguments: [ @validator.mapping.class_metadata_factory, @validator.validator_factory, @translator.default, %validator.translation_domain%, [] ]

    ite_form.form.form_type_extension:
        class:                                              %ite_form.form.form_type_extension.class%
        arguments: [ @session, %ite_form.timezone% ]
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.widget_form_type_extension:
        class:                                              %ite_form.form.widget_form_type_extension.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.daterange_type:
        class:                                              %ite_form.form.daterange_type.class%
        tags:
            - { name: form.type, alias: daterange }

    ite_form.form.bootstrap_date_picker_type:
        class:                                              %ite_form.form.bootstrap_date_picker_type.class%
        tags:
            - { name: form.type, alias: ite_bootstrap_date_picker }

    ite_form.form.bootstrap_datetime_picker_type:
        class:                                              %ite_form.form.bootstrap_datetime_picker_type.class%
        tags:
            - { name: form.type, alias: ite_bootstrap_datetime_picker }

    ite_form.form.bootstrap_time_picker_type:
        class:                                              %ite_form.form.bootstrap_time_picker_type.class%
        tags:
            - { name: form.type, alias: ite_bootstrap_time_picker }

    ite_form.form.ajax_entity_type:
        class:                                              %ite_form.form.ajax_entity_type.class%
        arguments: [ @router ]
        tags:
            - { name: form.type, alias: ite_ajax_entity }