parameters:
    ite_form.sf.extension.form.class:                    ITE\FormBundle\Service\SFFormExtension

    ite_form.twig.sf_extension.class:                    ITE\FormBundle\Twig\Extension\SFExtension

    ite_form.form.form_type_extension.class:             ITE\FormBundle\Form\Core\Extension\FormTypeExtension
    ite_form.form.collection_type_extension.class:       ITE\FormBundle\Form\Core\Extension\CollectionTypeExtension
    ite_form.form.button_type_extension.class:           ITE\FormBundle\Form\Core\Extension\ButtonTypeExtension

    ite_form.entity_converter.class:                     ITE\FormBundle\Service\EntityConverter

    ite_form.form.ajax_entity_type.class:                ITE\FormBundle\Form\Doctrine\Type\AjaxEntityType

    ite_form.form.input_entity_type.class:               ITE\FormBundle\Form\Doctrine\Type\InputEntityType
    ite_form.form.markup_type.class:                     ITE\FormBundle\Form\Core\Type\MarkupType

#    assetic.twig_extension.class:                        ITE\FormBundle\Twig\Extension\AsseticExtension
    assetic.asset_factory.class:                         ITE\FormBundle\Factory\AssetFactory
    form.resolved_type_factory.class:                    ITE\FormBundle\Form\ResolvedFormTypeFactory

#    refactor below
    ite_form.form_validator.class:                       ITE\FormBundle\Service\FormValidator
#    ite_form.form.daterange_type.class:                  ITE\FormBundle\Form\Core\Type\DateRangeType

services:
    ite_form.sf.extension.form:
        class:                                              %ite_form.sf.extension.form.class%
        tags:
            - { name: ite_js.sf.extension, alias: form }

    ite_form.twig.sf_extension:
        class:                                              %ite_form.twig.sf_extension.class%
        arguments: [ @ite_js.sf ]
        tags:
            - { name: twig.extension }

    ite_form.form.form_type_extension:
        class:                                              %ite_form.form.form_type_extension.class%
        arguments: [ @session, %ite_form.timezone% ]
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.collection_type_extension:
        class:                                              %ite_form.form.collection_type_extension.class%
        tags:
            - { name: form.type_extension, alias: collection }

    ite_form.form.button_type_extension:
        class:                                              %ite_form.form.button_type_extension.class%
        tags:
            - { name: form.type_extension, alias: button }

    ite_form.form.ajax_entity_type:
        class:                                              %ite_form.form.ajax_entity_type.class%
        arguments: [ @router ]
        tags:
            - { name: form.type, alias: ite_ajax_entity }

    ite_form.form.input_entity_type:
        class:                                              %ite_form.form.input_entity_type.class%
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: ite_input_entity }

    ite_form.form.markup_type:
        class:                                              %ite_form.form.markup_type.class%
        tags:
            - { name: form.type, alias: ite_markup }

    ite_form.entity_converter:
        class:                                              %ite_form.entity_converter.class%
        scope:                                              request
        arguments: [ @doctrine.orm.entity_manager, @request ]

#    refactor below
    ite_form.form_validator:
        class:                                              %ite_form.form_validator.class%
        arguments: [ @validator.mapping.class_metadata_factory, @validator.validator_factory, @translator.default, %validator.translation_domain%, [] ]

#    ite_form.form.daterange_type:
#        class:                                              %ite_form.form.daterange_type.class%
#        tags:
#            - { name: form.type, alias: daterange }