parameters:
    ite_form.sf.extension.form.class:                       ITE\FormBundle\SF\SFFormExtension
    ite_form.twig.sf_extension.class:                       ITE\FormBundle\Twig\Extension\SFExtension
    ite_form.param_protector.class:                         ITE\FormBundle\Service\Security\ParamProtector

services:
    ite_form.sf.extension.form:
        class:                                              %ite_form.sf.extension.form.class%
        arguments: [ @service_container ]
        tags:
            - { name: ite_js.sf.extension, alias: form }

    ite_form.twig.sf_extension:
        class:                                              %ite_form.twig.sf_extension.class%
        arguments: [ @ite_form.sf.extension.form ]
        tags:
            - { name: twig.extension }

    ite_form.param_protector:
        class:                                              %ite_form.param_protector.class%
        arguments: [ @session, %kernel.secret% ]