parameters:
    ite_form.form.type_extension.plugin.form.class:         ITE\FormBundle\Form\Extension\Plugin\FormTypeExtension
    ite_form.form.type_extension.timezone.class:            ITE\FormBundle\Form\Extension\FormTypeTimezoneExtension

services:
    ite_form.form.type_extension.plugin.form:
        class: %ite_form.form.type_extension.plugin.form.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.timezone:
        class: %ite_form.form.type_extension.timezone.class%
        arguments: [ @session, %ite_form.timezone% ]
        tags:
            - { name: form.type_extension, alias: form }