parameters:
    ite_form.form.type.ajax_choice.class:           ITE\FormBundle\Form\Type\AjaxChoiceType
    ite_form.form.type.ajax_entity.class:           ITE\FormBundle\Form\Type\AjaxEntityType
    ite_form.form.type.google_font.class:           ITE\FormBundle\Form\Type\GoogleFontType
    ite_form.form.type.range.class:                 ITE\FormBundle\Form\Type\RangeType
    ite_form.form.type.simple_range.class:          ITE\FormBundle\Form\Type\SimpleRangeType
    ite_form.form.type.boolean_hidden.class:        ITE\FormBundle\Form\Type\BooleanHiddenType

    # todo: refactor types below
    ite_form.form.input_entity_type.class:          ITE\FormBundle\Form\Type\InputEntityType
    ite_form.form.markup_type.class:                ITE\FormBundle\Form\Type\MarkupType

services:
    ite_form.form.type.ajax_choice:
        class: %ite_form.form.type.ajax_choice.class%
        arguments: [ @router ]
        tags:
            - { name: form.type, alias: ite_ajax_choice }

    ite_form.form.type.ajax_entity:
        class: %ite_form.form.type.ajax_entity.class%
        arguments: [ @doctrine ]
        tags:
            - { name: form.type, alias: ite_ajax_entity }

    ite_form.form.type.google_font:
        class: %ite_form.form.type.google_font.class%
        tags:
            - { name: form.type, alias: ite_google_font }

    ite_form.form.type.range:
        class: %ite_form.form.type.range.class%
        tags:
            - { name: form.type, alias: ite_range }

    ite_form.form.type.simple_range:
        class: %ite_form.form.type.simple_range.class%
        tags:
            - { name: form.type, alias: ite_simple_range }

    ite_form.form.input_entity_type:
        class: %ite_form.form.input_entity_type.class%
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: ite_input_entity }

    ite_form.form.markup_type:
        class: %ite_form.form.markup_type.class%
        tags:
            - { name: form.type, alias: ite_markup }

    ite_form.form.type.boolean_hidden:
        class: %ite_form.form.type.boolean_hidden.class%
        tags:
            - { name: form.type, alias: ite_boolean_hidden }