parameters:
    ite_form.form.type_extension.plugin.form.class:                             ITE\FormBundle\Form\Extension\Plugin\FormTypeExtension
    ite_form.form.type_extension.form.attr_callback.class:                      ITE\FormBundle\Form\Extension\FormTypeAttrCallbackExtension
    ite_form.form.type_extension.form.constraints_callback.class:               ITE\FormBundle\Form\Extension\FormTypeConstraintsCallbackExtension
    ite_form.form.type_extension.form.extras.class:                             ITE\FormBundle\Form\Extension\FormTypeExtrasExtension
    ite_form.form.type_extension.form.default_data.class:                       ITE\FormBundle\Form\Extension\FormTypeDefaultDataExtension
    ite_form.form.type_extension.form.form_view.class:                          ITE\FormBundle\Form\Extension\FormTypeFormViewExtension
    ite_form.form.type_extension.form.lifetime.class:                           ITE\FormBundle\Form\Extension\FormTypeLifetimeExtension
    ite_form.form.type_extension.collection.form_view.class:                    ITE\FormBundle\Form\Extension\CollectionTypeFormViewExtension
    ite_form.form.type_extension.choice.form_view.class:                        ITE\FormBundle\Form\Extension\ChoiceTypeFormViewExtension
    ite_form.form.type_extension.hidden.markup.class:                           ITE\FormBundle\Form\Extension\Hidden\HiddenTypeMarkupExtension
    ite_form.form.type_extension.entity.sort.class:                             ITE\FormBundle\Form\Extension\EntityTypeSortExtension
    ite_form.form.type_extension.form.original_configuration.class:             ITE\FormBundle\Form\Extension\FormTypeOriginalConfigurationExtension
    ite_form.form.type_extension.dynamic.default_configuration.abstract.class:  ITE\FormBundle\Form\Extension\AbstractDynamicTypeDefaultConfigurationExtension
    ite_form.form.type_extension.button.original_configuration.class:           ITE\FormBundle\Form\Extension\ButtonTypeOriginalConfigurationExtension

services:
    ite_form.form.type_extension.plugin.form:
        class: %ite_form.form.type_extension.plugin.form.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.form.attr_callback:
        class: %ite_form.form.type_extension.form.attr_callback.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.form.constraints_callback:
        class: %ite_form.form.type_extension.form.constraints_callback.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.form.extras:
        class: %ite_form.form.type_extension.form.extras.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.form.default_data:
        class: %ite_form.form.type_extension.form.default_data.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.form.form_view:
        class: %ite_form.form.type_extension.form.form_view.class%
        arguments: [ @ite_form.sf.extension.form, @ite_form.client_form_view_builder ]
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.form.lifetime:
        class: %ite_form.form.type_extension.form.lifetime.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.collection.form_view:
        class: %ite_form.form.type_extension.collection.form_view.class%
        arguments: [ @ite_form.client_form_view_builder ]
        tags:
            - { name: form.type_extension, alias: collection }

    ite_form.form.type_extension.choice.form_view:
        class: %ite_form.form.type_extension.choice.form_view.class%
        tags:
            - { name: form.type_extension, alias: choice }

    ite_form.form.type_extension.hidden.markup:
        class: %ite_form.form.type_extension.hidden.markup.class%
        arguments: [ @?ite_formatter ]
        tags:
            - { name: form.type_extension, alias: hidden }

    ite_form.form.type_extension.entity.sort:
        class: %ite_form.form.type_extension.entity.sort.class%
        tags:
            - { name: form.type_extension, alias: entity }

    ite_form.form.type_extension.form.original_configuration:
        class: %ite_form.form.type_extension.form.original_configuration.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.dynamic.default_configuration.abstract:
        class: %ite_form.form.type_extension.dynamic.default_configuration.abstract.class%
        abstract: true
        arguments:
            - null
            - {}

    ite_form.form.type_extension.button.original_configuration:
        class: %ite_form.form.type_extension.button.original_configuration.class%
        tags:
            - { name: form.type_extension, alias: button }
