parameters:
    ite_form.form.type.ajax_choice.class:           ITE\FormBundle\Form\Type\AjaxChoiceType
    ite_form.form.type.ajax_entity.class:           ITE\FormBundle\Form\Type\AjaxEntityType
    ite_form.form.type.google_font.class:           ITE\FormBundle\Form\Type\GoogleFontType

    # todo: refactor types below
    ite_form.form.markup_type.class:                ITE\FormBundle\Form\Type\MarkupType

services:
    ite_form.form.type.ajax_choice:
        class: %ite_form.form.type.ajax_choice.class%
        arguments: [ @router ]
        tags:
            - { name: form.type, alias: ite_ajax_choice }

    ite_form.form.type.ajax_entity:
        class: %ite_form.form.type.ajax_entity.class%
        arguments: [ @doctrine ]
        tags:
            - { name: form.type, alias: ite_ajax_entity }

    ite_form.form.type.google_font:
        class: %ite_form.form.type.google_font.class%
        tags:
            - { name: form.type, alias: ite_google_font }

    ite_form.form.markup_type:
        class: %ite_form.form.markup_type.class%
        tags:
            - { name: form.type, alias: ite_markup }