parameters:
    ite_form.form.type_extension.plugin.form.class:     ITE\FormBundle\Form\Extension\Plugin\FormTypeExtension
    ite_form.form.form_type_extension.class:            ITE\FormBundle\Form\Extension\FormTypeExtension

services:
    ite_form.form.type_extension.plugin.form:
        class: %ite_form.form.type_extension.plugin.form.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.form_type_extension:
        class: %ite_form.form.form_type_extension.class%
        arguments: [ @session, %ite_form.timezone% ]
        tags:
            - { name: form.type_extension, alias: form }
