parameters:
    ite_form.form.type.ajax_choice.class:           ITE\FormBundle\Form\Type\AjaxChoiceType
    ite_form.form.type.ajax_entity.class:           ITE\FormBundle\Form\Type\AjaxEntityType
    ite_form.form.type.ajax_file.class:             ITE\FormBundle\Form\Type\AjaxFileType
    ite_form.form.type.ajax_file_data.class:        ITE\FormBundle\Form\Type\AjaxFileDataType
    ite_form.form.type.mixed_entity.class:          ITE\FormBundle\Form\Type\MixedEntityType
    ite_form.form.type.ajax_mixed_entity.class:     ITE\FormBundle\Form\Type\AjaxMixedEntityType
    ite_form.form.type.google_font.class:           ITE\FormBundle\Form\Type\GoogleFontType
    ite_form.form.markup_type.class:                ITE\FormBundle\Form\Type\MarkupType
    ite_form.form.type.compound_datetime.class:     ITE\FormBundle\Form\Type\CompoundDatetimeType
    ite_form.form.type.dynamic.abstract.class:      ITE\FormBundle\Form\Type\AbstractDynamicType

services:
    ite_form.form.type.ajax_choice:
        class: %ite_form.form.type.ajax_choice.class%
        arguments: [ @router ]
        tags:
            - { name: form.type, alias: ite_ajax_choice }

    ite_form.form.type.ajax_entity:
        class: %ite_form.form.type.ajax_entity.class%
        arguments: [ @doctrine ]
        tags:
            - { name: form.type, alias: ite_ajax_entity }

    ite_form.form.type.ajax_file:
        class: %ite_form.form.type.ajax_file.class%
        arguments: [ @router, @request_stack ]
        tags:
            - { name: form.type, alias: ite_ajax_file }

    ite_form.form.type.ajax_file_data:
        class: %ite_form.form.type.ajax_file_data.class%
        arguments: [ %ite_form.component.ajax_file_upload.upload_dir% ]
        tags:
            - { name: form.type, alias: ite_ajax_file_data }

    ite_form.form.type.google_font:
        class: %ite_form.form.type.google_font.class%
        tags:
            - { name: form.type, alias: ite_google_font }

    ite_form.form.type.mixed_entity:
        class: %ite_form.form.type.mixed_entity.class%
        arguments: [ @form.factory ]
        tags:
            - { name: form.type, alias: ite_mixed_entity }

    ite_form.form.type.ajax_mixed_entity:
        class: %ite_form.form.type.ajax_mixed_entity.class%
        arguments: [ @doctrine, @router ]
        tags:
            - { name: form.type, alias: ite_ajax_mixed_entity }

    ite_form.form.markup_type:
        class: %ite_form.form.markup_type.class%
        arguments: [ @?ite_formatter ]
        tags:
            - { name: form.type, alias: ite_markup }

    ite_form.form.type.compound_datetime:
        class: %ite_form.form.type.compound_datetime.class%
        tags:
            - { name: form.type, alias: compound_datetime }

    ite_form.form.type.dynamic.abstract:
        class: %ite_form.form.type.dynamic.abstract.class%
        abstract: true
        arguments:
            - null
            - null
            - {}
