parameters:
    ite_form.form.type_extension.component.ajax_submit.class:   ITE\FormBundle\Form\Extension\Component\AjaxSubmit\FormTypeAjaxSubmitExtension

services:
    ite_form.form.type_extension.component.ajax_submit:
        class: %ite_form.form.type_extension.component.ajax_submit.class%
        arguments: [ %ite_form.component.ajax_submit.default_submitter% ]
        tags:
            - { name: form.type_extension, alias: form }