parameters:
    ite_form.form.type.ajax_file.class:             ITE\FormBundle\Form\Type\AjaxFileType
    ite_form.form.type.ajax_file_data.class:        ITE\FormBundle\Form\Type\AjaxFileDataType

services:
    ite_form.form.type.ajax_file:
        class: %ite_form.form.type.ajax_file.class%
        arguments: [ @router, @request_stack ]
        tags:
            - { name: form.type, alias: ite_ajax_file }

    ite_form.form.type.ajax_file_data:
        class: %ite_form.form.type.ajax_file_data.class%
        arguments: [ %ite_form.component.ajax_file_upload.upload_dir% ]
        tags:
            - { name: form.type, alias: ite_ajax_file_data }
