parameters:
    ite_form.form.type_extension.component.collection.collection.class: ITE\FormBundle\Form\Extension\Component\Collection\CollectionTypeCollectionExtension

services:
    ite_form.form.type_extension.component.collection.collection:
        class:                                                          %ite_form.form.type_extension.component.collection.collection.class%
        tags:
            - { name: form.type_extension, alias: collection }