parameters:
    ite_form.form.type_extension.component.dynamic_choice.choice.class: ITE\FormBundle\Form\Extension\Component\DynamicChoice\ChoiceTypeDynamicChoiceExtension
    ite_form.form.type_extension.component.dynamic_choice.entity.class: ITE\FormBundle\Form\Extension\Component\DynamicChoice\EntityTypeDynamicChoiceExtension

    ite_form.widget_generator.class:                                    ITE\FormBundle\Service\Widget\WidgetGenerator

services:
    ite_form.form.type_extension.component.dynamic_choice.choice:
        class: %ite_form.form.type_extension.component.dynamic_choice.choice.class%
        tags:
            - { name: form.type_extension, alias: choice }

    ite_form.form.type_extension.component.dynamic_choice.entity:
        class: %ite_form.form.type_extension.component.dynamic_choice.entity.class%
        tags:
            - { name: form.type_extension, alias: entity }

    ite_form.widget_generator:
        class: %ite_form.widget_generator.class%
        arguments: [ @form.factory ]