parameters:
    ite_form.form.type_extension.component.dynamic_choice.choice.class: ITE\FormBundle\Form\Extension\Component\DynamicChoice\ChoiceTypeDynamicChoiceExtension
    ite_form.form.type_extension.component.dynamic_choice.entity.class: ITE\FormBundle\Form\Extension\Component\DynamicChoice\EntityTypeDynamicChoiceExtension
    ite_form.form.type.component.dynamic_choice.ajax_entity.class:      ITE\FormBundle\Form\Type\Component\DynamicChoice\AjaxEntityType

    ite_form.entity_converter.class:                                    ITE\FormBundle\Service\Converter\EntityConverter
    ite_form.widget_generator.class:                                    ITE\FormBundle\Service\Widget\WidgetGenerator

services:
    ite_form.form.type_extension.component.dynamic_choice.choice:
        class:                                                          %ite_form.form.type_extension.component.dynamic_choice.choice.class%
        tags:
            - { name: form.type_extension, alias: choice }

    ite_form.form.type_extension.component.dynamic_choice.entity:
        class:                                                          %ite_form.form.type_extension.component.dynamic_choice.entity.class%
        tags:
            - { name: form.type_extension, alias: entity }

    ite_form.form.type.component.dynamic_choice.ajax_entity:
        class:                                                          %ite_form.form.type.component.dynamic_choice.ajax_entity.class%
        arguments: [ @router ]
        tags:
            - { name: form.type, alias: ite_ajax_entity }

    ite_form.entity_converter:
        class:                                                          %ite_form.entity_converter.class%
        arguments: [ @doctrine.orm.entity_manager, @request= ]

    ite_form.widget_generator:
        class:                                                          %ite_form.widget_generator.class%
        arguments: [ @form.factory ]