parameters:
    ite_form.editable_manager.class:                        ITE\FormBundle\Component\Editable\EditableManager
    ite_form.twig.extension.component.editable.class:       ITE\FormBundle\Twig\Extension\Component\Editable\EditableExtension

services:
    ite_form.editable_manager:
        class: %ite_form.editable_manager.class%
        arguments:
            - @doctrine
            - @router
            - @form.factory
            - @templating
            - @ite_formatter.manager
            - %ite_form.component.editable.defaults%

    ite_form.twig.extension.component.editable:
        class: %ite_form.twig.extension.component.editable.class%
        arguments:
            - @ite_form.editable_manager
        tags:
            - { name: twig.extension }
