parameters:
    ite_form.editable_manager.class:                        ITE\FormBundle\Service\Editable\EditableManager

services:
    ite_form.editable_manager:
        class:                                              %ite_form.editable_manager.class%
        arguments: [ @form.factory ]
