parameters:
    ite_form.form.type_extension.component.hierarchical.form.class: ITE\FormBundle\Form\Extension\Component\Hierarchical\FormTypeHierarchicalExtension

services:
    ite_form.form.type_extension.component.hierarchical.form:
        class: %ite_form.form.type_extension.component.hierarchical.form.class%
        arguments: [ @ite_form.sf.extension.form, @request_stack ]
        tags:
            - { name: form.type_extension, alias: form }