parameters:
    form.resolved_type_factory.class:                               ITE\FormBundle\Form\ResolvedFormTypeFactory

    ite_form.form.type_extension.component.ordered.form.class:      ITE\FormBundle\Form\Extension\Component\Ordered\FormTypeOrderedExtension
    ite_form.form.type_extension.component.ordered.button.class:    ITE\FormBundle\Form\Extension\Component\Ordered\ButtonTypeOrderedExtension

services:
    ite_form.form.type_extension.component.ordered.form:
        class:                                                      %ite_form.form.type_extension.component.ordered.form.class%
        tags:
            - { name: form.type_extension, alias: form }

    ite_form.form.type_extension.component.ordered.button:
        class:                                                      %ite_form.form.type_extension.component.ordered.button.class%
        tags:
            - { name: form.type_extension, alias: button }